#!/usr/bin/env bash
# Installs locklane into ~/.locklane (#289): downloads the current engine jar, asks the
# handful of settings a fresh install needs, and writes them to
# ~/.locklane/application-locklane.properties. Fetches update.sh alongside it for
# pulling a newer jar later without repeating any of this.
#
# The login account is created here and now, by running the jar once in its seed-only
# mode with the credentials in the environment (#384). The password is therefore never
# written to disk and never appears in `ps` output -- the properties file ends up
# holding only the port and the allowed origins.
#
# Usage: curl -fsSL <url-to-this-file> | bash
set -euo pipefail

# Mirrors engine/src/main/resources/application.yml's
# locklane.release-check.repository — the repo whose newest permanent release the
# in-app update banner announces; this script installs from that same channel (#465).
REPO="haninaguib-devtools/locklane"
INSTALL_DIR="${LOCKLANE_HOME:-$HOME/.locklane}"

if ! command -v gh >/dev/null 2>&1; then
  echo "error: the GitHub CLI (gh) is required — install it from https://cli.github.com." >&2
  exit 1
fi
# gh no longer needs to be logged in on this host (#551): every project acts as one of
# the GitHub accounts signed in through Locklane's own accounts page, not whatever
# identity gh happens to be authenticated as here. gh itself still has to be installed
# -- gh repo create and issue/PR fetches for a project with no account chosen still run
# through it.
# Needed by the installer itself, not just later: the seeding run below is this jar.
if ! command -v java >/dev/null 2>&1; then
  echo "error: java 21 or newer is required — install a JDK, then re-run this installer." >&2
  exit 1
fi
java_bin="$(command -v java)"

mkdir -p "$INSTALL_DIR"

# No tag argument: gh resolves the newest permanent (non-prerelease, non-draft)
# release — the same release the in-app update banner announces (#465).
echo "Downloading locklane.jar (newest release of $REPO)..."
gh release download --repo "$REPO" --pattern locklane.jar \
  --dir "$INSTALL_DIR" --clobber

echo "Fetching update.sh..."
gh api -H "Accept: application/vnd.github.raw" "repos/$REPO/contents/update.sh" \
  > "$INSTALL_DIR/update.sh"
chmod +x "$INSTALL_DIR/update.sh"

# --- The uninstaller (#392) ---------------------------------------------------
# Writes $1/uninstall.sh, with the install directory ($1), the service kind ($2:
# "systemd", "launchd", or empty for the detached fallback) and the unit/plist path
# ($3, empty for the fallback) baked in at generation time. It is generated rather
# than downloaded: an uninstaller that needs the network, a logged-in gh, and the
# repository to still exist is unavailable exactly when it is most wanted.
#
# THIS FUNCTION IS DUPLICATED, BYTE FOR BYTE, IN install.sh AND update.sh -- install.sh
# writes the uninstaller, update.sh rewrites it so an existing install never keeps a
# stale copy. Change one, change the other; the task's checks diff the two copies.
write_uninstall_script() {
  local dir="$1" kind="$2" reg="$3"
  # Bake in a resolved absolute path, never whatever spelling the caller happened to
  # use: LOCKLANE_HOME could be relative, or carry a trailing slash, and the generated
  # script's own guards can only be as good as the string they are given.
  dir="$(cd "$dir" && pwd -P)"
  local out="$dir/uninstall.sh"
  {
    # Expanded heredoc: only the three baked-in values. printf %q keeps a path with
    # a space or a quote in it from breaking the generated script.
    cat <<EOF
#!/usr/bin/env bash
# Uninstalls locklane (#392). Generated by install.sh at install time, rewritten by
# update.sh -- do not edit here; the next update overwrites it.
#
# Always stops the server and de-registers it from the service manager. Deleting the
# install directory is a separate, explicit decision: it holds the login accounts, the
# projects, and the database, and nothing here backs them up first.
#
# Usage: uninstall.sh [--service-only | --all] [--yes]
set -euo pipefail

INSTALL_DIR=$(printf %q "$dir")
SERVICE_KIND=$(printf %q "$kind")
REG_FILE=$(printf %q "$reg")
EOF
    # Quoted heredoc: everything below is the generated script's own runtime code and
    # must reach it unexpanded.
    cat <<'UNINSTALL_BODY'
AGENT_LABEL="com.locklane.server"

usage() {
  cat <<USAGE
Usage: uninstall.sh [--service-only | --all] [--yes]

  --service-only  Stop and de-register the server, keep $INSTALL_DIR and its data.
  --all           Also delete $INSTALL_DIR (accounts, projects, database).
  --yes           Skip the typed confirmation --all would otherwise ask for.

With no flag and no terminal to ask on, this exits without removing anything.
USAGE
}

mode=""
assume_yes=0
while [ $# -gt 0 ]; do
  case "$1" in
    --service-only) mode="service" ;;
    --all) mode="all" ;;
    --yes|-y) assume_yes=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "error: unknown option '$1'" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

# --- Stop the server and de-register it ---------------------------------------
# This half is unconditional: whatever the answer about the data, a service manager
# must not be left restarting a jar that may be about to disappear.

case "$SERVICE_KIND" in
  systemd)
    echo "Stopping and removing the systemd user service..."
    systemctl --user disable --now locklane 2>/dev/null || true
    ;;
  launchd)
    echo "Stopping and removing the launchd agent..."
    launchctl bootout "gui/$(id -u)/$AGENT_LABEL" 2>/dev/null || true
    ;;
  *)
    pid_file="$INSTALL_DIR/locklane.pid"
    if [ -f "$pid_file" ]; then
      old_pid="$(cat "$pid_file")"
      # A pid file naming a process that is already gone is not an error -- there is
      # simply nothing left to stop. Same bounded wait update.sh uses.
      if [ -n "$old_pid" ] && kill -0 "$old_pid" 2>/dev/null; then
        echo "Stopping the running server (pid $old_pid)..."
        kill "$old_pid"
        for _ in $(seq 1 30); do
          kill -0 "$old_pid" 2>/dev/null || break
          sleep 1
        done
        if kill -0 "$old_pid" 2>/dev/null; then
          echo "error: server (pid $old_pid) did not stop within 30s." >&2
          exit 1
        fi
      fi
      rm -f "$pid_file"
    fi
    ;;
esac

# Both well-known registration paths are swept, not just the one this install used: an
# install that set up a unit and later fell back would otherwise leave the first one
# behind, which is the restart loop this whole script exists to prevent.
rm -f "$REG_FILE"
rm -f "$HOME/.config/systemd/user/locklane.service"
rm -f "$HOME/Library/LaunchAgents/$AGENT_LABEL.plist"
if [ "$SERVICE_KIND" = "systemd" ] && command -v systemctl >/dev/null 2>&1; then
  systemctl --user daemon-reload 2>/dev/null || true
fi
echo "The server is stopped and no longer registered with any service manager."

# --- Decide about the data ----------------------------------------------------
# Reads from /dev/tty, not stdin (#354), so this still asks a person when the script
# is piped. No terminal and no flag means no guess: nothing is deleted.

if [ -z "$mode" ]; then
  # Opening it is the only honest test: /dev/tty exists and is mode-readable even in a
  # session with no controlling terminal, so -r would say yes and the read would fail.
  if ! : < /dev/tty 2>/dev/null; then
    echo "error: no terminal to ask on, and neither --service-only nor --all was given." >&2
    echo "Nothing was deleted. $INSTALL_DIR is still here." >&2
    exit 1
  fi
  cat <<PROMPT

$INSTALL_DIR holds everything locklane knows: your login accounts, the projects you
added, and the database they live in. Deleting it cannot be undone, and nothing here
makes a backup first.

PROMPT
  printf 'Type delete to remove it, or press Enter to keep it: '
  read -r answer < /dev/tty || answer=""
  if [ "$answer" = "delete" ]; then
    mode="all"
    assume_yes=1
  else
    mode="service"
  fi
fi

if [ "$mode" = "all" ] && [ "$assume_yes" -eq 0 ]; then
  # Opening it is the only honest test: /dev/tty exists and is mode-readable even in a
  # session with no controlling terminal, so -r would say yes and the read would fail.
  if ! : < /dev/tty 2>/dev/null; then
    echo "error: --all needs --yes when there is no terminal to confirm on." >&2
    echo "Nothing was deleted. $INSTALL_DIR is still here." >&2
    exit 1
  fi
  printf 'Type delete to remove %s and everything in it: ' "$INSTALL_DIR"
  read -r answer < /dev/tty || answer=""
  if [ "$answer" != "delete" ]; then
    echo "Not deleted."
    mode="service"
  fi
fi

if [ "$mode" != "all" ]; then
  cat <<KEPT
$INSTALL_DIR was kept, with your accounts, projects, and database in it.
Delete it later with: rm -rf $INSTALL_DIR

Nothing else on this machine was changed: the GitHub CLI and java are untouched,
and if 'loginctl enable-linger' was turned on at install time it is still on.
KEPT
  exit 0
fi

# --- Delete the install directory ---------------------------------------------
# Guarded: an empty INSTALL_DIR, / or $HOME would each turn the line below into a
# catastrophe rather than an uninstall.
#
# The guards compare RESOLVED paths, never the raw string. One directory has endlessly
# many spellings -- "$HOME/", "$HOME/.", "//home/you", a relative name, a symlink -- and
# a string comparison refuses only the exact spelling it was shown, while "$HOME/" walks
# straight past it and empties the home directory. Resolving first is what makes the
# refusal about the directory rather than about how it was typed.
case "$INSTALL_DIR" in
  "") echo "error: refusing to delete an empty path." >&2; exit 1 ;;
esac
if [ ! -d "$INSTALL_DIR" ]; then
  echo "$INSTALL_DIR is already gone."
  exit 0
fi
target="$(cd "$INSTALL_DIR" 2>/dev/null && pwd -P)" || target=""
home_real="$(cd "$HOME" 2>/dev/null && pwd -P)" || home_real="$HOME"
case "$target" in
  "") echo "error: could not resolve $INSTALL_DIR -- refusing to delete anything." >&2; exit 1 ;;
  "/") echo "error: refusing to delete /." >&2; exit 1 ;;
esac
if [ "$target" = "$home_real" ]; then
  echo "error: refusing to delete your home directory." >&2
  exit 1
fi
# From here on the resolved path is the only one used.
INSTALL_DIR="$target"

cat <<DONE
Deleting $INSTALL_DIR...

locklane is uninstalled. Nothing else on this machine was changed: the GitHub CLI and
java are untouched, and if 'loginctl enable-linger' was turned on at install time it is
still on -- turn it off with 'loginctl disable-linger' if nothing else needs it.
DONE

# Last statement in the script, deliberately: it deletes this file too.
rm -rf "$INSTALL_DIR"
UNINSTALL_BODY
  } > "$out"
  chmod +x "$out"
# The end marker is load-bearing: the generated script contains a `}` at column 0 of
# its own, so the checks that extract this function key off this line, not off `}`.
} # end write_uninstall_script

# --- Resolving the user's real PATH (#422) -------------------------------------
# A service manager (systemd, launchd) starts its unit/agent with its own minimal
# PATH, not the one an interactive login shell builds up (nvm, homebrew, a language
# version manager's shims, ...) -- so an AI CLI that's perfectly callable from a
# terminal is invisible to the service. Resolved from a LOGIN shell specifically
# (`-l`), the same PATH a freshly opened terminal gets, never this installer's own
# (possibly non-login, e.g. piped through `curl | bash`) environment.
#
# THIS FUNCTION IS DUPLICATED, BYTE FOR BYTE, IN install.sh AND update.sh -- see
# write_uninstall_script above for why. Change one, change the other.
resolve_login_path() {
  local resolved
  resolved="$("${SHELL:-/bin/sh}" -lc 'echo $PATH' 2>/dev/null)" || resolved=""
  if [ -z "$resolved" ]; then
    resolved="$PATH"
  fi
  printf '%s' "$resolved"
}

# --- Prompts ------------------------------------------------------------------

port=""
while true; do
  read -r -p "Port to run on [8080]: " port < /dev/tty
  port="${port:-8080}"
  case "$port" in
    ''|*[!0-9]*) echo "Enter a port number." >&2; continue ;;
  esac
  [ "$port" -ge 1 ] && [ "$port" -le 65535 ] && break
  echo "Port must be between 1 and 65535." >&2
done

read -r -p "Extra allowed origins, comma-separated (localhost:$port is always allowed) []: " extra_origins < /dev/tty
origins="http://localhost:$port"
if [ -n "$extra_origins" ]; then
  origins="$origins,$extra_origins"
fi

read -r -p "Bootstrap username [admin]: " username < /dev/tty
username="${username:-admin}"

password=""
while true; do
  read -r -s -p "Bootstrap password: " password < /dev/tty
  echo
  if [ -z "$password" ]; then
    echo "Password cannot be empty." >&2
    continue
  fi
  read -r -s -p "Confirm password: " password_confirm < /dev/tty
  echo
  if [ "$password" != "$password_confirm" ]; then
    echo "Passwords did not match — try again." >&2
    continue
  fi
  break
done

# --- Write the properties file ------------------------------------------------
# The credentials deliberately do not go in here (#384) — they are used once, by the
# seeding run below, and then forgotten. Mode 600 anyway: nothing is gained by making
# a config file wider than the account that owns it.

props_file="$INSTALL_DIR/application-locklane.properties"
: > "$props_file"
chmod 600 "$props_file"
{
  echo "server.port=$port"
  echo "locklane.security.allowed-origins=$origins"
} > "$props_file"

# --- Create the login account -------------------------------------------------
# One run of the jar that seeds the account and stops. The credentials go through the
# environment, never the command line, so they stay out of `ps`. Run from
# $INSTALL_DIR, exactly as the server itself will be, so both use the same database.
# Port 0 keeps this run off whatever port an already-running instance may hold.
# Exit 3 is UserBootstrapper.EXIT_ALREADY_SEEDED: the database already had an account,
# so what was typed above was not applied and saying otherwise would be a lie.

echo "Creating the login account..."
seed_log="$INSTALL_DIR/install-seed.log"
: > "$seed_log"
chmod 600 "$seed_log"
# stdin comes from /dev/null, not the terminal and not the pipe this script may itself
# be being read from under `curl | bash` (#354's lesson) -- java has no business
# reading either.
seed_status=0
(
  cd "$INSTALL_DIR"
  LOCKLANE_SECURITY_BOOTSTRAP_USERNAME="$username" \
  LOCKLANE_SECURITY_BOOTSTRAP_PASSWORD="$password" \
    java -jar locklane.jar \
      --locklane.security.seed-only=true \
      --server.port=0 \
      --spring.main.banner-mode=off
) < /dev/null > "$seed_log" 2>&1 || seed_status=$?
unset password password_confirm

case "$seed_status" in
  0)
    account_note="The account '$username' is ready — no password was stored anywhere on disk."
    ;;
  3)
    account_note="An account already existed here, so the username and password you just
entered were NOT applied — sign in with the account you already have."
    ;;
  *)
    echo "error: could not create the login account — the log is at $seed_log" >&2
    exit 1
    ;;
esac
rm -f "$seed_log"

# --- Install a per-user service, or fall back to a detached start (#385) -------
# A detached start only outlives the terminal that launched it: it never comes back
# after a reboot or a crash (#386). A systemd user unit (Linux) or launchd agent
# (macOS) gives it both, restarting it on its own; on any other platform, or if the
# service manager can't be set up (e.g. no session bus), it falls back to #385's
# plain nohup/disown start rather than failing. Output goes to a log file in either
# case, and for the fallback, the pid is recorded so update.sh can find it later.

log_file="$INSTALL_DIR/locklane.log"
pid_file="$INSTALL_DIR/locklane.pid"
service_kind=""
# The unit or plist path the uninstaller must delete; empty for the detached fallback.
reg_file=""
resolved_path="$(resolve_login_path)"

case "$(uname -s)" in
  Linux)
    if command -v systemctl >/dev/null 2>&1; then
      unit_dir="$HOME/.config/systemd/user"
      unit_file="$unit_dir/locklane.service"
      mkdir -p "$unit_dir"
      cat > "$unit_file" <<EOF
[Unit]
Description=locklane
After=network.target

[Service]
Type=simple
WorkingDirectory=$INSTALL_DIR
Environment=PATH=$resolved_path
ExecStart=$java_bin -jar $INSTALL_DIR/locklane.jar
Restart=always
RestartSec=5
StandardOutput=append:$log_file
StandardError=append:$log_file

[Install]
WantedBy=default.target
EOF
      echo "Installing the systemd user service..."
      if systemctl --user daemon-reload 2>/dev/null && systemctl --user enable --now locklane 2>/dev/null; then
        service_kind="systemd"
        reg_file="$unit_file"
        # Best-effort: lets the service start at boot even with nobody logged in.
        loginctl enable-linger "$USER" 2>/dev/null || true
      else
        echo "warning: could not start the systemd user service — falling back to a detached start." >&2
        rm -f "$unit_file"
      fi
    fi
    ;;
  Darwin)
    agent_dir="$HOME/Library/LaunchAgents"
    agent_label="com.locklane.server"
    agent_file="$agent_dir/$agent_label.plist"
    mkdir -p "$agent_dir"
    cat > "$agent_file" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$agent_label</string>
  <key>ProgramArguments</key>
  <array>
    <string>$java_bin</string>
    <string>-jar</string>
    <string>$INSTALL_DIR/locklane.jar</string>
  </array>
  <key>WorkingDirectory</key><string>$INSTALL_DIR</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key><string>$resolved_path</string>
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key><false/>
  </dict>
  <key>StandardOutPath</key><string>$log_file</string>
  <key>StandardErrorPath</key><string>$log_file</string>
</dict>
</plist>
EOF
    echo "Installing the launchd agent..."
    if launchctl bootstrap "gui/$(id -u)" "$agent_file" 2>/dev/null; then
      service_kind="launchd"
      reg_file="$agent_file"
    else
      echo "warning: could not load the launchd agent — falling back to a detached start." >&2
      rm -f "$agent_file"
    fi
    ;;
esac

if [ -z "$service_kind" ]; then
  echo "No per-user service manager available here — starting detached instead; it will not survive a reboot or a crash, so you'll need to restart it yourself."
  echo "Starting the server..."
  (
    cd "$INSTALL_DIR"
    nohup "$java_bin" -jar locklane.jar > "$log_file" 2>&1 < /dev/null &
    echo $! > "$pid_file"
    disown
  )
fi

# Written last, so it knows which of the three launch modes actually took effect.
write_uninstall_script "$INSTALL_DIR" "$service_kind" "$reg_file"

cat <<EOF

Installed to $INSTALL_DIR:
  locklane.jar
  update.sh
  uninstall.sh
  application-locklane.properties (mode 600; port and origins only)
  locklane.log (server output)

$account_note

The server is running on port $port. Output is logged to $log_file.
EOF

case "$service_kind" in
  systemd)
    cat <<EOF

It's installed as a systemd user service (locklane): it restarts on its own if killed
or if it crashes, and starts again at login or at boot.
  Status:  systemctl --user status locklane
  Stop:    systemctl --user stop locklane
  Remove:  systemctl --user disable --now locklane && rm -f "$unit_file" && systemctl --user daemon-reload
EOF
    ;;
  launchd)
    cat <<EOF

It's installed as a launchd agent ($agent_label): it restarts on its own if killed or
if it crashes, and starts again at login.
  Status:  launchctl print gui/$(id -u)/$agent_label
  Stop:    launchctl bootout gui/$(id -u)/$agent_label
  Remove:  launchctl bootout gui/$(id -u)/$agent_label; rm -f "$agent_file"
EOF
    ;;
esac

cat <<EOF

Later, pull a newer build with:
  $INSTALL_DIR/update.sh

To uninstall — this stops the server and de-registers it, then asks separately whether
to delete $INSTALL_DIR and the accounts, projects, and database in it:
  $INSTALL_DIR/uninstall.sh
EOF
