#!/usr/bin/env bash
# Pulls the newest released locklane.jar into this directory and relaunches it
# (#289). Run from ~/.locklane, where install.sh put things.
#
# The one edit it ever makes to application-locklane.properties is retiring the stored
# bootstrap password (#384) — see below. Nothing else in that file is touched.
set -euo pipefail

# Mirrors engine/src/main/resources/application.yml's
# locklane.release-check.repository — the repo whose newest permanent release the
# in-app update banner announces; this script updates from that same channel (#465).
REPO="haninaguib-devtools/locklane"

cd "$(dirname "$0")"

# --- The uninstaller (#392) ---------------------------------------------------
# Writes $1/uninstall.sh, with the install directory ($1), the service kind ($2:
# "systemd", "launchd", or empty for the detached fallback) and the unit/plist path
# ($3, empty for the fallback) baked in at generation time. It is generated rather
# than downloaded: an uninstaller that needs the network, a logged-in gh, and the
# repository to still exist is unavailable exactly when it is most wanted.
#
# THIS FUNCTION IS DUPLICATED, BYTE FOR BYTE, IN install.sh AND update.sh -- install.sh
# writes the uninstaller, update.sh rewrites it so an existing install never keeps a
# stale copy. Change one, change the other; the task's checks diff the two copies.
write_uninstall_script() {
  local dir="$1" kind="$2" reg="$3"
  # Bake in a resolved absolute path, never whatever spelling the caller happened to
  # use: LOCKLANE_HOME could be relative, or carry a trailing slash, and the generated
  # script's own guards can only be as good as the string they are given.
  dir="$(cd "$dir" && pwd -P)"
  local out="$dir/uninstall.sh"
  {
    # Expanded heredoc: only the three baked-in values. printf %q keeps a path with
    # a space or a quote in it from breaking the generated script.
    cat <<EOF
#!/usr/bin/env bash
# Uninstalls locklane (#392). Generated by install.sh at install time, rewritten by
# update.sh -- do not edit here; the next update overwrites it.
#
# Always stops the server and de-registers it from the service manager. Deleting the
# install directory is a separate, explicit decision: it holds the login accounts, the
# projects, and the database, and nothing here backs them up first.
#
# Usage: uninstall.sh [--service-only | --all] [--yes]
set -euo pipefail

INSTALL_DIR=$(printf %q "$dir")
SERVICE_KIND=$(printf %q "$kind")
REG_FILE=$(printf %q "$reg")
EOF
    # Quoted heredoc: everything below is the generated script's own runtime code and
    # must reach it unexpanded.
    cat <<'UNINSTALL_BODY'
AGENT_LABEL="com.locklane.server"

usage() {
  cat <<USAGE
Usage: uninstall.sh [--service-only | --all] [--yes]

  --service-only  Stop and de-register the server, keep $INSTALL_DIR and its data.
  --all           Also delete $INSTALL_DIR (accounts, projects, database).
  --yes           Skip the typed confirmation --all would otherwise ask for.

With no flag and no terminal to ask on, this exits without removing anything.
USAGE
}

mode=""
assume_yes=0
while [ $# -gt 0 ]; do
  case "$1" in
    --service-only) mode="service" ;;
    --all) mode="all" ;;
    --yes|-y) assume_yes=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "error: unknown option '$1'" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

# --- Stop the server and de-register it ---------------------------------------
# This half is unconditional: whatever the answer about the data, a service manager
# must not be left restarting a jar that may be about to disappear.

case "$SERVICE_KIND" in
  systemd)
    echo "Stopping and removing the systemd user service..."
    systemctl --user disable --now locklane 2>/dev/null || true
    ;;
  launchd)
    echo "Stopping and removing the launchd agent..."
    launchctl bootout "gui/$(id -u)/$AGENT_LABEL" 2>/dev/null || true
    ;;
  *)
    pid_file="$INSTALL_DIR/locklane.pid"
    if [ -f "$pid_file" ]; then
      old_pid="$(cat "$pid_file")"
      # A pid file naming a process that is already gone is not an error -- there is
      # simply nothing left to stop. Same bounded wait update.sh uses.
      if [ -n "$old_pid" ] && kill -0 "$old_pid" 2>/dev/null; then
        echo "Stopping the running server (pid $old_pid)..."
        kill "$old_pid"
        for _ in $(seq 1 30); do
          kill -0 "$old_pid" 2>/dev/null || break
          sleep 1
        done
        if kill -0 "$old_pid" 2>/dev/null; then
          echo "error: server (pid $old_pid) did not stop within 30s." >&2
          exit 1
        fi
      fi
      rm -f "$pid_file"
    fi
    ;;
esac

# Both well-known registration paths are swept, not just the one this install used: an
# install that set up a unit and later fell back would otherwise leave the first one
# behind, which is the restart loop this whole script exists to prevent.
rm -f "$REG_FILE"
rm -f "$HOME/.config/systemd/user/locklane.service"
rm -f "$HOME/Library/LaunchAgents/$AGENT_LABEL.plist"
if [ "$SERVICE_KIND" = "systemd" ] && command -v systemctl >/dev/null 2>&1; then
  systemctl --user daemon-reload 2>/dev/null || true
fi
echo "The server is stopped and no longer registered with any service manager."

# --- Decide about the data ----------------------------------------------------
# Reads from /dev/tty, not stdin (#354), so this still asks a person when the script
# is piped. No terminal and no flag means no guess: nothing is deleted.

if [ -z "$mode" ]; then
  # Opening it is the only honest test: /dev/tty exists and is mode-readable even in a
  # session with no controlling terminal, so -r would say yes and the read would fail.
  if ! : < /dev/tty 2>/dev/null; then
    echo "error: no terminal to ask on, and neither --service-only nor --all was given." >&2
    echo "Nothing was deleted. $INSTALL_DIR is still here." >&2
    exit 1
  fi
  cat <<PROMPT

$INSTALL_DIR holds everything locklane knows: your login accounts, the projects you
added, and the database they live in. Deleting it cannot be undone, and nothing here
makes a backup first.

PROMPT
  printf 'Type delete to remove it, or press Enter to keep it: '
  read -r answer < /dev/tty || answer=""
  if [ "$answer" = "delete" ]; then
    mode="all"
    assume_yes=1
  else
    mode="service"
  fi
fi

if [ "$mode" = "all" ] && [ "$assume_yes" -eq 0 ]; then
  # Opening it is the only honest test: /dev/tty exists and is mode-readable even in a
  # session with no controlling terminal, so -r would say yes and the read would fail.
  if ! : < /dev/tty 2>/dev/null; then
    echo "error: --all needs --yes when there is no terminal to confirm on." >&2
    echo "Nothing was deleted. $INSTALL_DIR is still here." >&2
    exit 1
  fi
  printf 'Type delete to remove %s and everything in it: ' "$INSTALL_DIR"
  read -r answer < /dev/tty || answer=""
  if [ "$answer" != "delete" ]; then
    echo "Not deleted."
    mode="service"
  fi
fi

if [ "$mode" != "all" ]; then
  cat <<KEPT
$INSTALL_DIR was kept, with your accounts, projects, and database in it.
Delete it later with: rm -rf $INSTALL_DIR

Nothing else on this machine was changed: the GitHub CLI and java are untouched,
and if 'loginctl enable-linger' was turned on at install time it is still on.
KEPT
  exit 0
fi

# --- Delete the install directory ---------------------------------------------
# Guarded: an empty INSTALL_DIR, / or $HOME would each turn the line below into a
# catastrophe rather than an uninstall.
#
# The guards compare RESOLVED paths, never the raw string. One directory has endlessly
# many spellings -- "$HOME/", "$HOME/.", "//home/you", a relative name, a symlink -- and
# a string comparison refuses only the exact spelling it was shown, while "$HOME/" walks
# straight past it and empties the home directory. Resolving first is what makes the
# refusal about the directory rather than about how it was typed.
case "$INSTALL_DIR" in
  "") echo "error: refusing to delete an empty path." >&2; exit 1 ;;
esac
if [ ! -d "$INSTALL_DIR" ]; then
  echo "$INSTALL_DIR is already gone."
  exit 0
fi
target="$(cd "$INSTALL_DIR" 2>/dev/null && pwd -P)" || target=""
home_real="$(cd "$HOME" 2>/dev/null && pwd -P)" || home_real="$HOME"
case "$target" in
  "") echo "error: could not resolve $INSTALL_DIR -- refusing to delete anything." >&2; exit 1 ;;
  "/") echo "error: refusing to delete /." >&2; exit 1 ;;
esac
if [ "$target" = "$home_real" ]; then
  echo "error: refusing to delete your home directory." >&2
  exit 1
fi
# From here on the resolved path is the only one used.
INSTALL_DIR="$target"

cat <<DONE
Deleting $INSTALL_DIR...

locklane is uninstalled. Nothing else on this machine was changed: the GitHub CLI and
java are untouched, and if 'loginctl enable-linger' was turned on at install time it is
still on -- turn it off with 'loginctl disable-linger' if nothing else needs it.
DONE

# Last statement in the script, deliberately: it deletes this file too.
rm -rf "$INSTALL_DIR"
UNINSTALL_BODY
  } > "$out"
  chmod +x "$out"
# The end marker is load-bearing: the generated script contains a `}` at column 0 of
# its own, so the checks that extract this function key off this line, not off `}`.
} # end write_uninstall_script

# --- The control scripts (#612) ------------------------------------------------
# Writes $1/status.sh, $1/start.sh and $1/stop.sh, with the install directory ($1),
# the service kind ($2: "systemd", "launchd", or empty for the detached fallback) and
# the unit/plist path ($3, empty for the fallback) baked in at generation time, so a
# person can check, stop and start the server without knowing which service manager
# the install uses or remembering the commands install.sh printed once. Like the
# uninstaller they need no network, no gh and no repository.
#
# THIS FUNCTION IS DUPLICATED, BYTE FOR BYTE, IN install.sh AND update.sh -- install.sh
# writes the three scripts, update.sh rewrites them so an existing install never keeps
# a stale copy. Change one, change the other; the task's checks diff the two copies.
write_control_scripts() {
  local dir="$1" kind="$2" reg="$3"
  # Resolved absolute path, for the same reason write_uninstall_script resolves it.
  dir="$(cd "$dir" && pwd -P)"
  local name desc
  for name in status start stop; do
    case "$name" in
      status) desc="Reports whether the locklane server is running: exit 0 if it is, non-zero if not." ;;
      start)  desc="Starts the locklane server the way it was installed. Already running is not an error." ;;
      stop)   desc="Stops the locklane server the way it was installed. Already stopped is not an error." ;;
    esac
    {
      # Expanded heredoc: only the three baked-in values and the one-line description.
      # printf %q keeps a path with a space or a quote in it from breaking the script.
      cat <<EOF
#!/usr/bin/env bash
# $desc
# Generated by install.sh at install time (#612), rewritten by update.sh -- do not edit
# here; the next update overwrites it. stop.sh then start.sh is the restart.
set -euo pipefail

INSTALL_DIR=$(printf %q "$dir")
SERVICE_KIND=$(printf %q "$kind")
REG_FILE=$(printf %q "$reg")
EOF
      # Quoted heredocs: everything below is the generated script's own runtime code
      # and must reach it unexpanded.
      case "$name" in
        status) cat <<'STATUS_BODY'
AGENT_LABEL="com.locklane.server"
LOG_FILE="$INSTALL_DIR/locklane.log"

case "$SERVICE_KIND" in
  systemd)
    # systemctl's own exit status is the answer: 0 while the service is active, 3 when
    # it is stopped -- and it prints the unit's state and recent log lines either way.
    systemctl --user --no-pager status locklane
    ;;
  launchd)
    # launchctl print fails when the agent is not loaded, which after stop.sh (bootout
    # unloads it) is exactly the stopped state; when it is loaded, its listing says
    # whether the server process itself is up.
    if ! listing="$(launchctl print "gui/$(id -u)/$AGENT_LABEL" 2>/dev/null)"; then
      echo "locklane is not running: the launchd agent ($AGENT_LABEL) is not loaded. start.sh loads it."
      exit 1
    fi
    if printf '%s\n' "$listing" | grep -Eq '^[[:space:]]*state = running'; then
      echo "locklane is running as the launchd agent $AGENT_LABEL. Output is logged to $LOG_FILE."
    else
      echo "The launchd agent $AGENT_LABEL is loaded but the server is not running right now (launchd relaunches it after a failed exit). Output is logged to $LOG_FILE."
      exit 1
    fi
    ;;
  *)
    # Detached fallback: the pid recorded at start is the only handle on the server. A
    # missing pid file or a pid that is gone means "not running", never an error.
    pid_file="$INSTALL_DIR/locklane.pid"
    if [ ! -f "$pid_file" ]; then
      echo "locklane is not running (no $pid_file). start.sh starts it."
      exit 1
    fi
    pid="$(cat "$pid_file")"
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
      echo "locklane is running detached (pid $pid). Output is logged to $LOG_FILE."
    else
      echo "locklane is not running (pid ${pid:-?} in $pid_file is gone). start.sh starts it."
      exit 1
    fi
    ;;
esac
STATUS_BODY
        ;;
        start) cat <<'START_BODY'
AGENT_LABEL="com.locklane.server"
LOG_FILE="$INSTALL_DIR/locklane.log"

case "$SERVICE_KIND" in
  systemd)
    # `start` on an already-running unit is a no-op that exits 0.
    echo "Starting the locklane service..."
    systemctl --user start locklane
    echo "Started. Check on it with status.sh; output is logged to $LOG_FILE."
    ;;
  launchd)
    # A loaded agent is already running (or about to be: KeepAlive relaunches it), and
    # bootstrapping it a second time would only fail, so say so and stop here.
    if launchctl print "gui/$(id -u)/$AGENT_LABEL" >/dev/null 2>&1; then
      echo "locklane is already running: the launchd agent ($AGENT_LABEL) is loaded."
      exit 0
    fi
    if [ ! -f "$REG_FILE" ]; then
      echo "error: the agent's plist $REG_FILE is missing -- run update.sh to recreate it." >&2
      exit 1
    fi
    echo "Starting the locklane agent..."
    launchctl bootstrap "gui/$(id -u)" "$REG_FILE"
    echo "Started. The agent is loaded again, so it also comes back at the next login."
    ;;
  *)
    # Detached fallback: an alive pid in the pid file means already running -- never
    # start a second copy on the same port.
    pid_file="$INSTALL_DIR/locklane.pid"
    if [ -f "$pid_file" ]; then
      pid="$(cat "$pid_file")"
      if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
        echo "locklane is already running detached (pid $pid)."
        exit 0
      fi
    fi
    if ! command -v java >/dev/null 2>&1; then
      echo "error: java is not on PATH -- install a JDK, then re-run start.sh." >&2
      exit 1
    fi
    # The same start install.sh and update.sh use: nohup ignores the SIGHUP the shell
    # sends its children on exit, and disown drops the job from the shell's own table.
    echo "Starting the server detached..."
    cd "$INSTALL_DIR"
    nohup java -jar locklane.jar > "$LOG_FILE" 2>&1 < /dev/null &
    echo $! > "$pid_file"
    disown
    echo "Started (pid $(cat "$pid_file")). It will not survive a reboot or a crash; run start.sh again afterwards. Output is logged to $LOG_FILE."
    ;;
esac
START_BODY
        ;;
        stop) cat <<'STOP_BODY'
AGENT_LABEL="com.locklane.server"

case "$SERVICE_KIND" in
  systemd)
    # `stop` leaves the unit enabled, so the server comes back at the next login or
    # boot on its own; start.sh brings it back sooner. Already stopped exits 0.
    echo "Stopping the locklane service..."
    systemctl --user stop locklane
    echo "Stopped. The service stays enabled and comes back at the next boot; start.sh brings it back now."
    ;;
  launchd)
    # bootout is the only way to stop a KeepAlive agent (a plain `launchctl stop` would
    # just have launchd relaunch it), and it also UNLOADS the agent. A stopped agent
    # therefore stays down after bootout, and does not come back at the next login until
    # start.sh (or update.sh) bootstraps it again. That is the price of a stop that
    # actually sticks; start.sh restores the installed state.
    if ! launchctl print "gui/$(id -u)/$AGENT_LABEL" >/dev/null 2>&1; then
      echo "locklane is already stopped: the launchd agent ($AGENT_LABEL) is not loaded."
      exit 0
    fi
    echo "Stopping the locklane agent..."
    launchctl bootout "gui/$(id -u)/$AGENT_LABEL"
    echo "Stopped. The agent is unloaded, so it will not come back at the next login until start.sh (or update.sh) loads it again."
    ;;
  *)
    # Detached fallback: kill the recorded pid and wait for it to go, the same bounded
    # wait update.sh uses. A missing pid file or a pid that is already gone is not an
    # error -- there is simply nothing left to stop.
    pid_file="$INSTALL_DIR/locklane.pid"
    if [ ! -f "$pid_file" ]; then
      echo "locklane is already stopped (no $pid_file)."
      exit 0
    fi
    pid="$(cat "$pid_file")"
    if [ -z "$pid" ] || ! kill -0 "$pid" 2>/dev/null; then
      rm -f "$pid_file"
      echo "locklane is already stopped (pid ${pid:-?} in $pid_file was gone)."
      exit 0
    fi
    echo "Stopping the running server (pid $pid)..."
    kill "$pid"
    for _ in $(seq 1 30); do
      kill -0 "$pid" 2>/dev/null || break
      sleep 1
    done
    if kill -0 "$pid" 2>/dev/null; then
      echo "error: server (pid $pid) did not stop within 30s." >&2
      exit 1
    fi
    rm -f "$pid_file"
    echo "Stopped. It was started detached, so nothing restarts it on its own; start.sh does."
    ;;
esac
STOP_BODY
        ;;
      esac
    } > "$dir/$name.sh"
    chmod +x "$dir/$name.sh"
  done
# The end marker is load-bearing, as for write_uninstall_script: the generated scripts
# contain a `}` of their own, so the checks extracting this function key off this line.
} # end write_control_scripts

# --- Resolving the user's real PATH (#422) -------------------------------------
# A service manager (systemd, launchd) starts its unit/agent with its own minimal
# PATH, not the one an interactive login shell builds up (nvm, homebrew, a language
# version manager's shims, ...) -- so an AI CLI that's perfectly callable from a
# terminal is invisible to the service. Resolved from a LOGIN shell specifically
# (`-l`), the same PATH a freshly opened terminal gets, never this script's own
# (possibly non-login) environment.
#
# THIS FUNCTION IS DUPLICATED, BYTE FOR BYTE, IN install.sh AND update.sh -- see
# write_uninstall_script above for why. Change one, change the other.
resolve_login_path() {
  local resolved
  resolved="$("${SHELL:-/bin/sh}" -lc 'echo $PATH' 2>/dev/null)" || resolved=""
  if [ -z "$resolved" ]; then
    resolved="$PATH"
  fi
  printf '%s' "$resolved"
}

# Rewrites (or, on a pre-#422 install, adds) the systemd unit's Environment=PATH= line
# with a freshly resolved value -- so re-running update.sh repairs an already-broken
# service without a reinstall. Rewritten line by line rather than with sed: the PATH
# value is attacker-free but arbitrary, and this sidesteps having to escape it for a
# sed pattern/replacement or an `a` command's own text-continuation rules.
#
# Two distinct passes, not one combined pass: a combined pass that both replaces an
# existing `Environment=PATH=` line and inserts one after `[Service]` double-writes it
# when a unit already has the line, since it hits both the `[Service]` and the
# `Environment=PATH=` cases for the same file.
update_systemd_path() {
  local unit="$1" path_value="$2" tmp line
  tmp="$(mktemp "$unit.XXXXXX")"
  if grep -q '^Environment=PATH=' "$unit"; then
    while IFS= read -r line || [ -n "$line" ]; do
      case "$line" in
        Environment=PATH=*) printf 'Environment=PATH=%s\n' "$path_value" ;;
        *) printf '%s\n' "$line" ;;
      esac
    done < "$unit" > "$tmp"
  else
    while IFS= read -r line || [ -n "$line" ]; do
      printf '%s\n' "$line"
      if [ "$line" = '[Service]' ]; then
        printf 'Environment=PATH=%s\n' "$path_value"
      fi
    done < "$unit" > "$tmp"
  fi
  mv "$tmp" "$unit"
}

# Rewrites (or, on a pre-#422 install, adds) the launchd plist's EnvironmentVariables
# PATH entry with a freshly resolved value, via PlistBuddy -- the standard macOS tool
# for editing a plist without hand-rolling XML, and one that handles a PATH value
# containing spaces or colons correctly as long as it's quoted in the command string.
update_launchd_path() {
  local plist="$1" path_value="$2"
  /usr/libexec/PlistBuddy -c "Delete :EnvironmentVariables" "$plist" >/dev/null 2>&1 || true
  /usr/libexec/PlistBuddy -c "Add :EnvironmentVariables dict" "$plist"
  /usr/libexec/PlistBuddy -c "Add :EnvironmentVariables:PATH string \"$path_value\"" "$plist"
}

# --- Detect how the server was started (#386) -----------------------------------
# install.sh sets up a systemd user service or a launchd agent when the platform
# supports one, falling back to #385's plain detached start otherwise. Whichever it
# is, this script must stop and restart it the same way — never leave the service
# running while also launching a second, competing copy by hand.

unit_file="$HOME/.config/systemd/user/locklane.service"
agent_label="com.locklane.server"
agent_file="$HOME/Library/LaunchAgents/$agent_label.plist"
if [ -f "$unit_file" ] && command -v systemctl >/dev/null 2>&1; then
  service_kind="systemd"
elif [ -f "$agent_file" ] && command -v launchctl >/dev/null 2>&1; then
  service_kind="launchd"
else
  service_kind=""
fi

# --- Refresh the service's PATH (#422) -----------------------------------------
# Done here, before anything else touches the service, so an already-broken install
# is repaired by this run whether or not a newer jar is even available yet.
case "$service_kind" in
  systemd)
    echo "Refreshing the systemd service's PATH..."
    update_systemd_path "$unit_file" "$(resolve_login_path)"
    systemctl --user daemon-reload 2>/dev/null || true
    ;;
  launchd)
    echo "Refreshing the launchd agent's PATH..."
    update_launchd_path "$agent_file" "$(resolve_login_path)"
    ;;
esac

# gh must be installed, not logged in: the only gh call below is `gh release download`,
# which works unauthenticated on a public repository (#610).
if ! command -v gh >/dev/null 2>&1; then
  echo "error: the GitHub CLI (gh) is required — install it from https://cli.github.com." >&2
  exit 1
fi

# --- Retire a stored bootstrap password ---------------------------------------
# Installs predating #384 left the login password in plaintext here. The engine
# consumed it on its very first start and has ignored it ever since, so the value is
# dead — drop that one line and leave every other byte of the file as it was.

props_file="application-locklane.properties"
if [ -f "$props_file" ] && grep -Eq '^locklane\.security\.bootstrap-password[[:space:]]*=' "$props_file"; then
  echo "Removing the stored bootstrap password from $props_file..."
  tmp_props="$(mktemp "$props_file.XXXXXX")"
  chmod 600 "$tmp_props"
  sed -E '/^locklane\.security\.bootstrap-password[[:space:]]*=/d' "$props_file" > "$tmp_props"
  mv "$tmp_props" "$props_file"
fi

# --- Stop the running instance, if any -----------------------------------------
# Must happen before the jar is replaced (#385): overwriting locklane.jar with
# --clobber while the running JVM still holds that file open, then starting a second
# server on the port the first one still has bound, leaves the old server damaged and
# the new one not running. A missing pid file, or a pid that is no longer running, is
# not an error -- there is simply nothing to stop.

pid_file="locklane.pid"
case "$service_kind" in
  systemd)
    echo "Stopping the locklane service..."
    systemctl --user stop locklane
    ;;
  launchd)
    echo "Stopping the locklane agent..."
    # bootout also fully unloads it, which is what lets the KeepAlive agent stay down
    # for the download below instead of relaunching itself immediately.
    launchctl bootout "gui/$(id -u)/$agent_label" 2>/dev/null || true
    ;;
  *)
    if [ -f "$pid_file" ]; then
      old_pid="$(cat "$pid_file")"
      if [ -n "$old_pid" ] && kill -0 "$old_pid" 2>/dev/null; then
        echo "Stopping the running server (pid $old_pid)..."
        kill "$old_pid"
        for _ in $(seq 1 30); do
          kill -0 "$old_pid" 2>/dev/null || break
          sleep 1
        done
        if kill -0 "$old_pid" 2>/dev/null; then
          echo "error: server (pid $old_pid) did not stop within 30s." >&2
          exit 1
        fi
      fi
      rm -f "$pid_file"
    fi
    ;;
esac

# No tag argument: gh resolves the newest permanent (non-prerelease, non-draft)
# release — the same release the in-app update banner announces (#465).
echo "Downloading locklane.jar (newest release of $REPO)..."
gh release download --repo "$REPO" --pattern locklane.jar \
  --dir . --clobber

# --- Start the new build ---------------------------------------------------------
# A service-managed install (#386) is restarted the same way it was started; the
# fallback (#385) relaunches detached the same way install.sh does: nohup ignores the
# SIGHUP the shell sends its children on exit, and disown drops it from the shell's own
# job table, the second, independent way a closing terminal can take a background job
# down with it.

case "$service_kind" in
  systemd)
    echo "Restarting the locklane service..."
    systemctl --user start locklane
    ;;
  launchd)
    echo "Restarting the locklane agent..."
    launchctl bootstrap "gui/$(id -u)" "$agent_file"
    ;;
  *)
    log_file="locklane.log"
    echo "Relaunching..."
    nohup java -jar locklane.jar > "$log_file" 2>&1 < /dev/null &
    echo $! > "$pid_file"
    disown
    ;;
esac

# --- Refresh the uninstaller (#392) and the control scripts (#612) ---------------
# Rewritten on every update so an install never keeps a stale copy -- one generated
# before the service kind changed would de-register, stop or start the wrong thing, or
# nothing.

case "$service_kind" in
  systemd) reg_file="$unit_file" ;;
  launchd) reg_file="$agent_file" ;;
  *) reg_file="" ;;
esac
write_uninstall_script "$(pwd)" "$service_kind" "$reg_file"
write_control_scripts "$(pwd)" "$service_kind" "$reg_file"
