#!/usr/bin/env bash
# Pulls the current locklane.jar (latest build) into this directory and relaunches it
# (#289). Run from ~/.locklane, where install.sh put things.
#
# The one edit it ever makes to application-locklane.properties is retiring the stored
# bootstrap password (#384) — see below. Nothing else in that file is touched.
set -euo pipefail

# Mirrors engine/src/main/resources/application.yml's
# locklane.release-check.repository — the only release channel that exists today.
REPO="haninaguib-devtools/locklane"

cd "$(dirname "$0")"

# --- The uninstaller (#392) ---------------------------------------------------
# Writes $1/uninstall.sh, with the install directory ($1), the service kind ($2:
# "systemd", "launchd", or empty for the detached fallback) and the unit/plist path
# ($3, empty for the fallback) baked in at generation time. It is generated rather
# than downloaded: an uninstaller that needs the network, a logged-in gh, and the
# repository to still exist is unavailable exactly when it is most wanted.
#
# THIS FUNCTION IS DUPLICATED, BYTE FOR BYTE, IN install.sh AND update.sh -- install.sh
# writes the uninstaller, update.sh rewrites it so an existing install never keeps a
# stale copy. Change one, change the other; the task's checks diff the two copies.
write_uninstall_script() {
  local dir="$1" kind="$2" reg="$3"
  local out="$dir/uninstall.sh"
  {
    # Expanded heredoc: only the three baked-in values. printf %q keeps a path with
    # a space or a quote in it from breaking the generated script.
    cat <<EOF
#!/usr/bin/env bash
# Uninstalls locklane (#392). Generated by install.sh at install time, rewritten by
# update.sh -- do not edit here; the next update overwrites it.
#
# Always stops the server and de-registers it from the service manager. Deleting the
# install directory is a separate, explicit decision: it holds the login accounts, the
# projects, and the database, and nothing here backs them up first.
#
# Usage: uninstall.sh [--service-only | --all] [--yes]
set -euo pipefail

INSTALL_DIR=$(printf %q "$dir")
SERVICE_KIND=$(printf %q "$kind")
REG_FILE=$(printf %q "$reg")
EOF
    # Quoted heredoc: everything below is the generated script's own runtime code and
    # must reach it unexpanded.
    cat <<'UNINSTALL_BODY'
AGENT_LABEL="com.locklane.server"

usage() {
  cat <<USAGE
Usage: uninstall.sh [--service-only | --all] [--yes]

  --service-only  Stop and de-register the server, keep $INSTALL_DIR and its data.
  --all           Also delete $INSTALL_DIR (accounts, projects, database).
  --yes           Skip the typed confirmation --all would otherwise ask for.

With no flag and no terminal to ask on, this exits without removing anything.
USAGE
}

mode=""
assume_yes=0
while [ $# -gt 0 ]; do
  case "$1" in
    --service-only) mode="service" ;;
    --all) mode="all" ;;
    --yes|-y) assume_yes=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "error: unknown option '$1'" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

# --- Stop the server and de-register it ---------------------------------------
# This half is unconditional: whatever the answer about the data, a service manager
# must not be left restarting a jar that may be about to disappear.

case "$SERVICE_KIND" in
  systemd)
    echo "Stopping and removing the systemd user service..."
    systemctl --user disable --now locklane 2>/dev/null || true
    ;;
  launchd)
    echo "Stopping and removing the launchd agent..."
    launchctl bootout "gui/$(id -u)/$AGENT_LABEL" 2>/dev/null || true
    ;;
  *)
    pid_file="$INSTALL_DIR/locklane.pid"
    if [ -f "$pid_file" ]; then
      old_pid="$(cat "$pid_file")"
      # A pid file naming a process that is already gone is not an error -- there is
      # simply nothing left to stop. Same bounded wait update.sh uses.
      if [ -n "$old_pid" ] && kill -0 "$old_pid" 2>/dev/null; then
        echo "Stopping the running server (pid $old_pid)..."
        kill "$old_pid"
        for _ in $(seq 1 30); do
          kill -0 "$old_pid" 2>/dev/null || break
          sleep 1
        done
        if kill -0 "$old_pid" 2>/dev/null; then
          echo "error: server (pid $old_pid) did not stop within 30s." >&2
          exit 1
        fi
      fi
      rm -f "$pid_file"
    fi
    ;;
esac

# Both well-known registration paths are swept, not just the one this install used: an
# install that set up a unit and later fell back would otherwise leave the first one
# behind, which is the restart loop this whole script exists to prevent.
rm -f "$REG_FILE"
rm -f "$HOME/.config/systemd/user/locklane.service"
rm -f "$HOME/Library/LaunchAgents/$AGENT_LABEL.plist"
if [ "$SERVICE_KIND" = "systemd" ] && command -v systemctl >/dev/null 2>&1; then
  systemctl --user daemon-reload 2>/dev/null || true
fi
echo "The server is stopped and no longer registered with any service manager."

# --- Decide about the data ----------------------------------------------------
# Reads from /dev/tty, not stdin (#354), so this still asks a person when the script
# is piped. No terminal and no flag means no guess: nothing is deleted.

if [ -z "$mode" ]; then
  # Opening it is the only honest test: /dev/tty exists and is mode-readable even in a
  # session with no controlling terminal, so -r would say yes and the read would fail.
  if ! : < /dev/tty 2>/dev/null; then
    echo "error: no terminal to ask on, and neither --service-only nor --all was given." >&2
    echo "Nothing was deleted. $INSTALL_DIR is still here." >&2
    exit 1
  fi
  cat <<PROMPT

$INSTALL_DIR holds everything locklane knows: your login accounts, the projects you
added, and the database they live in. Deleting it cannot be undone, and nothing here
makes a backup first.

PROMPT
  printf 'Type delete to remove it, or press Enter to keep it: '
  read -r answer < /dev/tty || answer=""
  if [ "$answer" = "delete" ]; then
    mode="all"
    assume_yes=1
  else
    mode="service"
  fi
fi

if [ "$mode" = "all" ] && [ "$assume_yes" -eq 0 ]; then
  # Opening it is the only honest test: /dev/tty exists and is mode-readable even in a
  # session with no controlling terminal, so -r would say yes and the read would fail.
  if ! : < /dev/tty 2>/dev/null; then
    echo "error: --all needs --yes when there is no terminal to confirm on." >&2
    echo "Nothing was deleted. $INSTALL_DIR is still here." >&2
    exit 1
  fi
  printf 'Type delete to remove %s and everything in it: ' "$INSTALL_DIR"
  read -r answer < /dev/tty || answer=""
  if [ "$answer" != "delete" ]; then
    echo "Not deleted."
    mode="service"
  fi
fi

if [ "$mode" != "all" ]; then
  cat <<KEPT
$INSTALL_DIR was kept, with your accounts, projects, and database in it.
Delete it later with: rm -rf $INSTALL_DIR

Nothing else on this machine was changed: the GitHub CLI and java are untouched,
and if 'loginctl enable-linger' was turned on at install time it is still on.
KEPT
  exit 0
fi

# --- Delete the install directory ---------------------------------------------
# Guarded: an empty INSTALL_DIR, / or $HOME would each turn the line below into a
# catastrophe rather than an uninstall.
case "$INSTALL_DIR" in
  "") echo "error: refusing to delete an empty path." >&2; exit 1 ;;
  "/") echo "error: refusing to delete /." >&2; exit 1 ;;
esac
if [ "$INSTALL_DIR" = "$HOME" ]; then
  echo "error: refusing to delete your home directory." >&2
  exit 1
fi
if [ ! -d "$INSTALL_DIR" ]; then
  echo "$INSTALL_DIR is already gone."
  exit 0
fi

cat <<DONE
Deleting $INSTALL_DIR...

locklane is uninstalled. Nothing else on this machine was changed: the GitHub CLI and
java are untouched, and if 'loginctl enable-linger' was turned on at install time it is
still on -- turn it off with 'loginctl disable-linger' if nothing else needs it.
DONE

# Last statement in the script, deliberately: it deletes this file too.
rm -rf "$INSTALL_DIR"
UNINSTALL_BODY
  } > "$out"
  chmod +x "$out"
# The end marker is load-bearing: the generated script contains a `}` at column 0 of
# its own, so the checks that extract this function key off this line, not off `}`.
} # end write_uninstall_script

# --- Detect how the server was started (#386) -----------------------------------
# install.sh sets up a systemd user service or a launchd agent when the platform
# supports one, falling back to #385's plain detached start otherwise. Whichever it
# is, this script must stop and restart it the same way — never leave the service
# running while also launching a second, competing copy by hand.

unit_file="$HOME/.config/systemd/user/locklane.service"
agent_label="com.locklane.server"
agent_file="$HOME/Library/LaunchAgents/$agent_label.plist"
if [ -f "$unit_file" ] && command -v systemctl >/dev/null 2>&1; then
  service_kind="systemd"
elif [ -f "$agent_file" ] && command -v launchctl >/dev/null 2>&1; then
  service_kind="launchd"
else
  service_kind=""
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "error: the GitHub CLI (gh) is required — install it from https://cli.github.com, then run 'gh auth login'." >&2
  exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  echo "error: gh is not logged in — run 'gh auth login' first." >&2
  exit 1
fi

# --- Retire a stored bootstrap password ---------------------------------------
# Installs predating #384 left the login password in plaintext here. The engine
# consumed it on its very first start and has ignored it ever since, so the value is
# dead — drop that one line and leave every other byte of the file as it was.

props_file="application-locklane.properties"
if [ -f "$props_file" ] && grep -Eq '^locklane\.security\.bootstrap-password[[:space:]]*=' "$props_file"; then
  echo "Removing the stored bootstrap password from $props_file..."
  tmp_props="$(mktemp "$props_file.XXXXXX")"
  chmod 600 "$tmp_props"
  sed -E '/^locklane\.security\.bootstrap-password[[:space:]]*=/d' "$props_file" > "$tmp_props"
  mv "$tmp_props" "$props_file"
fi

# --- Stop the running instance, if any -----------------------------------------
# Must happen before the jar is replaced (#385): overwriting locklane.jar with
# --clobber while the running JVM still holds that file open, then starting a second
# server on the port the first one still has bound, leaves the old server damaged and
# the new one not running. A missing pid file, or a pid that is no longer running, is
# not an error -- there is simply nothing to stop.

pid_file="locklane.pid"
case "$service_kind" in
  systemd)
    echo "Stopping the locklane service..."
    systemctl --user stop locklane
    ;;
  launchd)
    echo "Stopping the locklane agent..."
    # bootout also fully unloads it, which is what lets the KeepAlive agent stay down
    # for the download below instead of relaunching itself immediately.
    launchctl bootout "gui/$(id -u)/$agent_label" 2>/dev/null || true
    ;;
  *)
    if [ -f "$pid_file" ]; then
      old_pid="$(cat "$pid_file")"
      if [ -n "$old_pid" ] && kill -0 "$old_pid" 2>/dev/null; then
        echo "Stopping the running server (pid $old_pid)..."
        kill "$old_pid"
        for _ in $(seq 1 30); do
          kill -0 "$old_pid" 2>/dev/null || break
          sleep 1
        done
        if kill -0 "$old_pid" 2>/dev/null; then
          echo "error: server (pid $old_pid) did not stop within 30s." >&2
          exit 1
        fi
      fi
      rm -f "$pid_file"
    fi
    ;;
esac

echo "Downloading locklane.jar (latest build of $REPO)..."
gh release download latest --repo "$REPO" --pattern locklane.jar \
  --dir . --clobber

# --- Start the new build ---------------------------------------------------------
# A service-managed install (#386) is restarted the same way it was started; the
# fallback (#385) relaunches detached the same way install.sh does: nohup ignores the
# SIGHUP the shell sends its children on exit, and disown drops it from the shell's own
# job table, the second, independent way a closing terminal can take a background job
# down with it.

case "$service_kind" in
  systemd)
    echo "Restarting the locklane service..."
    systemctl --user start locklane
    ;;
  launchd)
    echo "Restarting the locklane agent..."
    launchctl bootstrap "gui/$(id -u)" "$agent_file"
    ;;
  *)
    log_file="locklane.log"
    echo "Relaunching..."
    nohup java -jar locklane.jar > "$log_file" 2>&1 < /dev/null &
    echo $! > "$pid_file"
    disown
    ;;
esac

# --- Refresh the uninstaller (#392) ----------------------------------------------
# Rewritten on every update so an install never keeps a stale copy -- one generated
# before the service kind changed would de-register the wrong thing, or nothing.

case "$service_kind" in
  systemd) reg_file="$unit_file" ;;
  launchd) reg_file="$agent_file" ;;
  *) reg_file="" ;;
esac
write_uninstall_script "$(pwd)" "$service_kind" "$reg_file"
