#!/usr/bin/env bash
# Pulls the newest released locklane.jar into this directory and relaunches it
# (#289). Run from ~/.locklane, where install.sh put things.
#
# The one edit it ever makes to application-locklane.properties is retiring the stored
# bootstrap password (#384) — see below. Nothing else in that file is touched.
set -euo pipefail

# Mirrors engine/src/main/resources/application.yml's
# locklane.release-check.repository — the repo whose newest permanent release the
# in-app update banner announces; this script updates from that same channel (#465).
REPO="haninaguib-devtools/locklane"

cd "$(dirname "$0")"

# --- The uninstaller (#392) ---------------------------------------------------
# Writes $1/uninstall.sh, with the install directory ($1), the service kind ($2:
# "systemd", "launchd", or empty for the detached fallback) and the unit/plist path
# ($3, empty for the fallback) baked in at generation time. It is generated rather
# than downloaded: an uninstaller that needs the network, a logged-in gh, and the
# repository to still exist is unavailable exactly when it is most wanted.
#
# THIS FUNCTION IS DUPLICATED, BYTE FOR BYTE, IN install.sh AND update.sh -- install.sh
# writes the uninstaller, update.sh rewrites it so an existing install never keeps a
# stale copy. Change one, change the other; the task's checks diff the two copies.
write_uninstall_script() {
  local dir="$1" kind="$2" reg="$3"
  # Bake in a resolved absolute path, never whatever spelling the caller happened to
  # use: LOCKLANE_HOME could be relative, or carry a trailing slash, and the generated
  # script's own guards can only be as good as the string they are given.
  dir="$(cd "$dir" && pwd -P)"
  local out="$dir/uninstall.sh"
  {
    # Expanded heredoc: only the three baked-in values. printf %q keeps a path with
    # a space or a quote in it from breaking the generated script.
    cat <<EOF
#!/usr/bin/env bash
# Uninstalls locklane (#392). Generated by install.sh at install time, rewritten by
# update.sh -- do not edit here; the next update overwrites it.
#
# Always stops the server and de-registers it from the service manager. Deleting the
# install directory is a separate, explicit decision: it holds the login accounts, the
# projects, and the database, and nothing here backs them up first.
#
# Usage: uninstall.sh [--service-only | --all] [--yes]
set -euo pipefail

INSTALL_DIR=$(printf %q "$dir")
SERVICE_KIND=$(printf %q "$kind")
REG_FILE=$(printf %q "$reg")
EOF
    # The console guard (#647), then the quoted heredoc: everything below it is the
    # generated script's own runtime code and must reach it unexpanded.
    write_inside_server_guard
    cat <<'UNINSTALL_BODY'
AGENT_LABEL="com.locklane.server"

usage() {
  cat <<USAGE
Usage: uninstall.sh [--service-only | --all] [--yes]

  --service-only  Stop and de-register the server, keep $INSTALL_DIR and its data.
  --all           Also delete $INSTALL_DIR (accounts, projects, database).
  --yes           Skip the typed confirmation --all would otherwise ask for.

With no flag and no terminal to ask on, this exits without removing anything.
USAGE
}

mode=""
assume_yes=0
while [ $# -gt 0 ]; do
  case "$1" in
    --service-only) mode="service" ;;
    --all) mode="all" ;;
    --yes|-y) assume_yes=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "error: unknown option '$1'" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

# Never from inside the server this would stop (#647): see refuse_inside_server above.
refuse_inside_server "$SERVICE_KIND" uninstall.sh "$AGENT_LABEL"

# --- Stop the server and de-register it ---------------------------------------
# This half is unconditional: whatever the answer about the data, a service manager
# must not be left restarting a jar that may be about to disappear.

case "$SERVICE_KIND" in
  systemd)
    echo "Stopping and removing the systemd user service..."
    systemctl --user disable --now locklane 2>/dev/null || true
    ;;
  launchd)
    echo "Stopping and removing the launchd agent..."
    launchctl bootout "gui/$(id -u)/$AGENT_LABEL" 2>/dev/null || true
    ;;
  *)
    pid_file="$INSTALL_DIR/locklane.pid"
    if [ -f "$pid_file" ]; then
      old_pid="$(cat "$pid_file")"
      # A pid file naming a process that is already gone is not an error -- there is
      # simply nothing left to stop. Same bounded wait update.sh uses.
      if [ -n "$old_pid" ] && kill -0 "$old_pid" 2>/dev/null; then
        echo "Stopping the running server (pid $old_pid)..."
        kill "$old_pid"
        for _ in $(seq 1 30); do
          kill -0 "$old_pid" 2>/dev/null || break
          sleep 1
        done
        if kill -0 "$old_pid" 2>/dev/null; then
          echo "error: server (pid $old_pid) did not stop within 30s." >&2
          exit 1
        fi
      fi
      rm -f "$pid_file"
    fi
    ;;
esac

# Both well-known registration paths are swept, not just the one this install used: an
# install that set up a unit and later fell back would otherwise leave the first one
# behind, which is the restart loop this whole script exists to prevent.
rm -f "$REG_FILE"
rm -f "$HOME/.config/systemd/user/locklane.service"
rm -f "$HOME/Library/LaunchAgents/$AGENT_LABEL.plist"
if [ "$SERVICE_KIND" = "systemd" ] && command -v systemctl >/dev/null 2>&1; then
  systemctl --user daemon-reload 2>/dev/null || true
fi
echo "The server is stopped and no longer registered with any service manager."

# --- Decide about the data ----------------------------------------------------
# Reads from /dev/tty, not stdin (#354), so this still asks a person when the script
# is piped. No terminal and no flag means no guess: nothing is deleted.

if [ -z "$mode" ]; then
  # Opening it is the only honest test: /dev/tty exists and is mode-readable even in a
  # session with no controlling terminal, so -r would say yes and the read would fail.
  if ! : < /dev/tty 2>/dev/null; then
    echo "error: no terminal to ask on, and neither --service-only nor --all was given." >&2
    echo "Nothing was deleted. $INSTALL_DIR is still here." >&2
    exit 1
  fi
  cat <<PROMPT

$INSTALL_DIR holds everything locklane knows: your login accounts, the projects you
added, and the database they live in. Deleting it cannot be undone, and nothing here
makes a backup first.

PROMPT
  printf 'Type delete to remove it, or press Enter to keep it: '
  read -r answer < /dev/tty || answer=""
  if [ "$answer" = "delete" ]; then
    mode="all"
    assume_yes=1
  else
    mode="service"
  fi
fi

if [ "$mode" = "all" ] && [ "$assume_yes" -eq 0 ]; then
  # Opening it is the only honest test: /dev/tty exists and is mode-readable even in a
  # session with no controlling terminal, so -r would say yes and the read would fail.
  if ! : < /dev/tty 2>/dev/null; then
    echo "error: --all needs --yes when there is no terminal to confirm on." >&2
    echo "Nothing was deleted. $INSTALL_DIR is still here." >&2
    exit 1
  fi
  printf 'Type delete to remove %s and everything in it: ' "$INSTALL_DIR"
  read -r answer < /dev/tty || answer=""
  if [ "$answer" != "delete" ]; then
    echo "Not deleted."
    mode="service"
  fi
fi

if [ "$mode" != "all" ]; then
  cat <<KEPT
$INSTALL_DIR was kept, with your accounts, projects, and database in it.
Delete it later with: rm -rf $INSTALL_DIR

Nothing else on this machine was changed: the GitHub CLI and java are untouched,
and if 'loginctl enable-linger' was turned on at install time it is still on.
KEPT
  exit 0
fi

# --- Delete the install directory ---------------------------------------------
# Guarded: an empty INSTALL_DIR, / or $HOME would each turn the line below into a
# catastrophe rather than an uninstall.
#
# The guards compare RESOLVED paths, never the raw string. One directory has endlessly
# many spellings -- "$HOME/", "$HOME/.", "//home/you", a relative name, a symlink -- and
# a string comparison refuses only the exact spelling it was shown, while "$HOME/" walks
# straight past it and empties the home directory. Resolving first is what makes the
# refusal about the directory rather than about how it was typed.
case "$INSTALL_DIR" in
  "") echo "error: refusing to delete an empty path." >&2; exit 1 ;;
esac
if [ ! -d "$INSTALL_DIR" ]; then
  echo "$INSTALL_DIR is already gone."
  exit 0
fi
target="$(cd "$INSTALL_DIR" 2>/dev/null && pwd -P)" || target=""
home_real="$(cd "$HOME" 2>/dev/null && pwd -P)" || home_real="$HOME"
case "$target" in
  "") echo "error: could not resolve $INSTALL_DIR -- refusing to delete anything." >&2; exit 1 ;;
  "/") echo "error: refusing to delete /." >&2; exit 1 ;;
esac
if [ "$target" = "$home_real" ]; then
  echo "error: refusing to delete your home directory." >&2
  exit 1
fi
# From here on the resolved path is the only one used.
INSTALL_DIR="$target"

cat <<DONE
Deleting $INSTALL_DIR...

locklane is uninstalled. Nothing else on this machine was changed: the GitHub CLI and
java are untouched, and if 'loginctl enable-linger' was turned on at install time it is
still on -- turn it off with 'loginctl disable-linger' if nothing else needs it.
DONE

# Last statement in the script, deliberately: it deletes this file too.
rm -rf "$INSTALL_DIR"
UNINSTALL_BODY
  } > "$out"
  chmod +x "$out"
# The end marker is load-bearing: the generated script contains a `}` at column 0 of
# its own, so the checks that extract this function key off this line, not off `}`.
} # end write_uninstall_script

# --- The control scripts (#612) ------------------------------------------------
# Writes $1/status.sh, $1/start.sh and $1/stop.sh, with the install directory ($1),
# the service kind ($2: "systemd", "launchd", or empty for the detached fallback) and
# the unit/plist path ($3, empty for the fallback) baked in at generation time, so a
# person can check, stop and start the server without knowing which service manager
# the install uses or remembering the commands install.sh printed once. Like the
# uninstaller they need no network, no gh and no repository.
#
# THIS FUNCTION IS DUPLICATED, BYTE FOR BYTE, IN install.sh AND update.sh -- install.sh
# writes the three scripts, update.sh rewrites them so an existing install never keeps
# a stale copy. Change one, change the other; the task's checks diff the two copies.
write_control_scripts() {
  local dir="$1" kind="$2" reg="$3"
  # Resolved absolute path, for the same reason write_uninstall_script resolves it.
  dir="$(cd "$dir" && pwd -P)"
  local name desc
  for name in status start stop; do
    case "$name" in
      status) desc="Reports whether the locklane server is running: exit 0 if it is, non-zero if not." ;;
      start)  desc="Starts the locklane server the way it was installed. Already running is not an error." ;;
      stop)   desc="Stops the locklane server the way it was installed. Already stopped is not an error." ;;
    esac
    {
      # Expanded heredoc: only the three baked-in values and the one-line description.
      # printf %q keeps a path with a space or a quote in it from breaking the script.
      cat <<EOF
#!/usr/bin/env bash
# $desc
# Generated by install.sh at install time (#612), rewritten by update.sh -- do not edit
# here; the next update overwrites it. stop.sh then start.sh is the restart.
set -euo pipefail

INSTALL_DIR=$(printf %q "$dir")
SERVICE_KIND=$(printf %q "$kind")
REG_FILE=$(printf %q "$reg")
EOF
      # Only stop.sh stops anything, so only it carries the console guard (#647).
      if [ "$name" = stop ]; then
        write_inside_server_guard
      fi
      # Quoted heredocs: everything below is the generated script's own runtime code
      # and must reach it unexpanded.
      case "$name" in
        status) cat <<'STATUS_BODY'
AGENT_LABEL="com.locklane.server"
LOG_FILE="$INSTALL_DIR/locklane.log"

case "$SERVICE_KIND" in
  systemd)
    # systemctl's own exit status is the answer: 0 while the service is active, 3 when
    # it is stopped -- and it prints the unit's state and recent log lines either way.
    systemctl --user --no-pager status locklane
    ;;
  launchd)
    # launchctl print fails when the agent is not loaded, which after stop.sh (bootout
    # unloads it) is exactly the stopped state; when it is loaded, its listing says
    # whether the server process itself is up.
    if ! listing="$(launchctl print "gui/$(id -u)/$AGENT_LABEL" 2>/dev/null)"; then
      echo "locklane is not running: the launchd agent ($AGENT_LABEL) is not loaded. start.sh loads it."
      exit 1
    fi
    if printf '%s\n' "$listing" | grep -Eq '^[[:space:]]*state = running'; then
      echo "locklane is running as the launchd agent $AGENT_LABEL. Output is logged to $LOG_FILE."
    else
      echo "The launchd agent $AGENT_LABEL is loaded but the server is not running right now (launchd relaunches it after a failed exit). Output is logged to $LOG_FILE."
      exit 1
    fi
    ;;
  *)
    # Detached fallback: the pid recorded at start is the only handle on the server. A
    # missing pid file or a pid that is gone means "not running", never an error.
    pid_file="$INSTALL_DIR/locklane.pid"
    if [ ! -f "$pid_file" ]; then
      echo "locklane is not running (no $pid_file). start.sh starts it."
      exit 1
    fi
    pid="$(cat "$pid_file")"
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
      echo "locklane is running detached (pid $pid). Output is logged to $LOG_FILE."
    else
      echo "locklane is not running (pid ${pid:-?} in $pid_file is gone). start.sh starts it."
      exit 1
    fi
    ;;
esac
STATUS_BODY
        ;;
        start) cat <<'START_BODY'
AGENT_LABEL="com.locklane.server"
LOG_FILE="$INSTALL_DIR/locklane.log"

case "$SERVICE_KIND" in
  systemd)
    # `start` on an already-running unit is a no-op that exits 0.
    echo "Starting the locklane service..."
    systemctl --user start locklane
    echo "Started. Check on it with status.sh; output is logged to $LOG_FILE."
    ;;
  launchd)
    # A loaded agent is already running (or about to be: KeepAlive relaunches it), and
    # bootstrapping it a second time would only fail, so say so and stop here.
    if launchctl print "gui/$(id -u)/$AGENT_LABEL" >/dev/null 2>&1; then
      echo "locklane is already running: the launchd agent ($AGENT_LABEL) is loaded."
      exit 0
    fi
    if [ ! -f "$REG_FILE" ]; then
      echo "error: the agent's plist $REG_FILE is missing -- run update.sh to recreate it." >&2
      exit 1
    fi
    echo "Starting the locklane agent..."
    launchctl bootstrap "gui/$(id -u)" "$REG_FILE"
    echo "Started. The agent is loaded again, so it also comes back at the next login."
    ;;
  *)
    # Detached fallback: an alive pid in the pid file means already running -- never
    # start a second copy on the same port.
    pid_file="$INSTALL_DIR/locklane.pid"
    if [ -f "$pid_file" ]; then
      pid="$(cat "$pid_file")"
      if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
        echo "locklane is already running detached (pid $pid)."
        exit 0
      fi
    fi
    if ! command -v java >/dev/null 2>&1; then
      echo "error: java is not on PATH -- install a JDK, then re-run start.sh." >&2
      exit 1
    fi
    # The same start install.sh and update.sh use: nohup ignores the SIGHUP the shell
    # sends its children on exit, and disown drops the job from the shell's own table.
    echo "Starting the server detached..."
    cd "$INSTALL_DIR"
    nohup java -jar locklane.jar > "$LOG_FILE" 2>&1 < /dev/null &
    echo $! > "$pid_file"
    disown
    echo "Started (pid $(cat "$pid_file")). It will not survive a reboot or a crash; run start.sh again afterwards. Output is logged to $LOG_FILE."
    ;;
esac
START_BODY
        ;;
        stop) cat <<'STOP_BODY'
AGENT_LABEL="com.locklane.server"

# Never from inside the server this would stop (#647): see refuse_inside_server above.
refuse_inside_server "$SERVICE_KIND" stop.sh "$AGENT_LABEL"

case "$SERVICE_KIND" in
  systemd)
    # `stop` leaves the unit enabled, so the server comes back at the next login or
    # boot on its own; start.sh brings it back sooner. Already stopped exits 0.
    echo "Stopping the locklane service..."
    systemctl --user stop locklane
    echo "Stopped. The service stays enabled and comes back at the next boot; start.sh brings it back now."
    ;;
  launchd)
    # bootout is the only way to stop a KeepAlive agent (a plain `launchctl stop` would
    # just have launchd relaunch it), and it also UNLOADS the agent. A stopped agent
    # therefore stays down after bootout, and does not come back at the next login until
    # start.sh (or update.sh) bootstraps it again. That is the price of a stop that
    # actually sticks; start.sh restores the installed state.
    domain="gui/$(id -u)/$AGENT_LABEL"
    if ! listing="$(launchctl print "$domain" 2>/dev/null)"; then
      echo "locklane is already stopped: the launchd agent ($AGENT_LABEL) is not loaded."
      exit 0
    fi
    # bootout returns before the process has gone (#647): wait, bounded to 30s, for
    # the agent to leave the domain and its pid to exit, so a start.sh straight after
    # does not fail with "Bootstrap failed: 5: Input/output error".
    pid="$(printf '%s\n' "$listing" | sed -n 's/^[[:space:]]*pid = \([0-9][0-9]*\).*/\1/p' | head -n 1)"
    echo "Stopping the locklane agent..."
    launchctl bootout "$domain"
    for _ in $(seq 1 30); do
      if ! launchctl print "$domain" >/dev/null 2>&1 \
          && { [ -z "$pid" ] || ! kill -0 "$pid" 2>/dev/null; }; then
        break
      fi
      sleep 1
    done
    forced=""
    if launchctl print "$domain" >/dev/null 2>&1 || { [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; }; then
      # The grace period is over (#676): the JVM, or a child holding it up, has ignored
      # SIGTERM for 30s. Finish the job the way systemd's own stop does -- SIGKILL, to
      # the service if launchd still has it and to the pid directly -- then give it a
      # few seconds more. A stop that ends here is still a stop, and says it was forced.
      echo "The server has not exited after 30s -- forcing it."
      launchctl kill SIGKILL "$domain" 2>/dev/null || true
      if [ -n "$pid" ]; then
        kill -KILL "$pid" 2>/dev/null || true
      fi
      for _ in $(seq 1 10); do
        if ! launchctl print "$domain" >/dev/null 2>&1 \
            && { [ -z "$pid" ] || ! kill -0 "$pid" 2>/dev/null; }; then
          break
        fi
        sleep 1
      done
      forced=" (forced after 30s: the server ignored SIGTERM)"
    fi
    if launchctl print "$domain" >/dev/null 2>&1 || { [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; }; then
      # Even SIGKILL did not clear it: say exactly what is left, so the next report is
      # not as blind as the one that led here (#676).
      {
        echo "error: the launchd agent $AGENT_LABEL did not stop, even when forced."
        if launchctl print "$domain" >/dev/null 2>&1; then
          echo "  agent: still loaded in $domain"
        else
          echo "  agent: unloaded"
        fi
        if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
          echo "  server pid $pid: still alive"
          echo "  its children: $(pgrep -P "$pid" 2>/dev/null | tr '\n' ' ')"
        else
          echo "  server pid ${pid:-?}: gone"
        fi
      } >&2
      exit 1
    fi
    echo "Stopped$forced. The agent is unloaded, so it will not come back at the next login until start.sh (or update.sh) loads it again."
    ;;
  *)
    # Detached fallback: kill the recorded pid and wait for it to go, the same bounded
    # wait update.sh uses. A missing pid file or a pid that is already gone is not an
    # error -- there is simply nothing left to stop.
    pid_file="$INSTALL_DIR/locklane.pid"
    if [ ! -f "$pid_file" ]; then
      echo "locklane is already stopped (no $pid_file)."
      exit 0
    fi
    pid="$(cat "$pid_file")"
    if [ -z "$pid" ] || ! kill -0 "$pid" 2>/dev/null; then
      rm -f "$pid_file"
      echo "locklane is already stopped (pid ${pid:-?} in $pid_file was gone)."
      exit 0
    fi
    echo "Stopping the running server (pid $pid)..."
    kill "$pid"
    for _ in $(seq 1 30); do
      kill -0 "$pid" 2>/dev/null || break
      sleep 1
    done
    forced=""
    if kill -0 "$pid" 2>/dev/null; then
      # The grace period is over (#676): finish the job the way systemd's own stop
      # does -- SIGKILL, then a few seconds more -- and say the stop was forced.
      echo "The server has not exited after 30s -- forcing it."
      kill -KILL "$pid" 2>/dev/null || true
      for _ in $(seq 1 10); do
        kill -0 "$pid" 2>/dev/null || break
        sleep 1
      done
      forced=" (forced after 30s: the server ignored SIGTERM)"
    fi
    if kill -0 "$pid" 2>/dev/null; then
      # Even SIGKILL did not clear it: say exactly what is left (#676). The pid file
      # is kept, since the process it names is still there.
      {
        echo "error: server (pid $pid) did not stop, even when forced."
        echo "  server pid $pid: still alive; $pid_file kept"
        echo "  its children: $(pgrep -P "$pid" 2>/dev/null | tr '\n' ' ')"
      } >&2
      exit 1
    fi
    rm -f "$pid_file"
    echo "Stopped$forced. It was started detached, so nothing restarts it on its own; start.sh does."
    ;;
esac
STOP_BODY
        ;;
      esac
    } > "$dir/$name.sh"
    chmod +x "$dir/$name.sh"
  done
# The end marker is load-bearing, as for write_uninstall_script: the generated scripts
# contain a `}` of their own, so the checks extracting this function key off this line.
} # end write_control_scripts

# --- The console guard, for the generated scripts (#647) ------------------------
# Prints the same refuse_inside_server function the scripts above define, for
# stop.sh and uninstall.sh to carry: they are standalone files that cannot source it.
# Kept in step with refuse_inside_server by hand -- a change to one is a change to
# both -- and, like every generator here, duplicated byte for byte in install.sh and
# update.sh. Change one, change the other.
write_inside_server_guard() {
  cat <<'GUARD_BODY'
# Refuses to run from inside the server this script would stop (#647): a Locklane
# console tab's shell is a child of the server JVM, and stopping the server from it
# ends this script mid-way, with nothing left to restart the server.
refuse_inside_server() {
  local kind="$1" script="$2" label="$3" agent_pid p
  case "$kind" in
    systemd)
      grep -qs 'locklane\.service' /proc/self/cgroup || return 0
      ;;
    launchd)
      agent_pid="$(launchctl print "gui/$(id -u)/$label" 2>/dev/null \
        | sed -n 's/^[[:space:]]*pid = \([0-9][0-9]*\).*/\1/p' | head -n 1)"
      if [ -z "$agent_pid" ]; then
        return 0
      fi
      p=$$
      while [ -n "$p" ] && [ "$p" -gt 1 ] && [ "$p" != "$agent_pid" ]; do
        p="$(ps -o ppid= -p "$p" 2>/dev/null | tr -d '[:space:]')"
      done
      if [ "$p" != "$agent_pid" ]; then
        return 0
      fi
      ;;
    *)
      return 0
      ;;
  esac
  cat >&2 <<REFUSED
error: not run -- $script is inside a Locklane console tab (or the IDE terminal opened
from one), which is inside the very server it would stop.
Stopping the server from here would end this shell too, and nothing here would finish.
Run $script from ssh or a local terminal instead. Nothing was changed.
REFUSED
  exit 2
} # end refuse_inside_server
GUARD_BODY
} # end write_inside_server_guard

# --- Resolving the user's real PATH (#422) -------------------------------------
# A service manager (systemd, launchd) starts its unit/agent with its own minimal
# PATH, not the one an interactive login shell builds up (nvm, homebrew, a language
# version manager's shims, ...) -- so an AI CLI that's perfectly callable from a
# terminal is invisible to the service. Resolved from a LOGIN shell specifically
# (`-l`), the same PATH a freshly opened terminal gets, never this script's own
# (possibly non-login) environment.
#
# The value is read from ONE tagged line, never from the shell's whole stdout (#672):
# a startup file that prints -- a greeting in ~/.zprofile, a version manager's banner,
# a `clear` in ~/.bash_logout on the way out -- lands in the same stream, and a
# newline is not a PATH separator, so the whole capture would become one broken entry
# and a gh that every terminal finds would be invisible to the service. No tagged line
# at all (the shell failed, or never ran the command) falls back to this script's own
# PATH, as before.
#
# THIS FUNCTION IS DUPLICATED, BYTE FOR BYTE, IN install.sh AND update.sh -- see
# write_uninstall_script above for why. Change one, change the other.
resolve_login_path() {
  local resolved
  resolved="$("${SHELL:-/bin/sh}" -lc 'printf "\n__LOCKLANE_PATH__=%s\n" "$PATH"' 2>/dev/null \
    | sed -n 's/^__LOCKLANE_PATH__=//p' | tail -n 1)" || resolved=""
  case "$resolved" in
    */*) ;;
    *) resolved="$PATH" ;;
  esac
  printf '%s' "$resolved"
} # end resolve_login_path

# --- Refusing to run from inside the server (#647) ------------------------------
# A Locklane console tab's shell is a child of the server JVM. On Linux it sits in the
# locklane.service cgroup, which `systemctl --user stop` sweeps wholesale (KillMode's
# default is control-group); on macOS it descends from the agent's pid, which
# `launchctl bootout` takes down with the agent. A script that stops the server from
# such a shell kills itself at its own stop step, and the server stays down with
# nothing left to restart it -- an explicit stop is exactly what Restart=always and
# KeepAlive do not undo. So every script that stops the server refuses to start from
# there, before it has changed anything. The detached fallback has no service manager
# sweeping a process tree, so it needs no guard. Exit 2, distinct from the 1 a stop
# that timed out returns: "refused to start" is not "tried and failed".
#
# THIS FUNCTION IS DUPLICATED, BYTE FOR BYTE, IN install.sh AND update.sh -- see
# write_uninstall_script above for why. Change one, change the other.
refuse_inside_server() {
  local kind="$1" script="$2" label="$3" agent_pid p
  case "$kind" in
    systemd)
      grep -qs 'locklane\.service' /proc/self/cgroup || return 0
      ;;
    launchd)
      agent_pid="$(launchctl print "gui/$(id -u)/$label" 2>/dev/null \
        | sed -n 's/^[[:space:]]*pid = \([0-9][0-9]*\).*/\1/p' | head -n 1)"
      if [ -z "$agent_pid" ]; then
        return 0
      fi
      p=$$
      while [ -n "$p" ] && [ "$p" -gt 1 ] && [ "$p" != "$agent_pid" ]; do
        p="$(ps -o ppid= -p "$p" 2>/dev/null | tr -d '[:space:]')"
      done
      if [ "$p" != "$agent_pid" ]; then
        return 0
      fi
      ;;
    *)
      return 0
      ;;
  esac
  cat >&2 <<REFUSED
error: not run -- $script is inside a Locklane console tab (or the IDE terminal opened
from one), which is inside the very server it would stop.
Stopping the server from here would end this shell too, and nothing here would finish.
Run $script from ssh or a local terminal instead. Nothing was changed.
REFUSED
  exit 2
} # end refuse_inside_server

# --- Stopping the launchd agent so that it stays stopped (#647) -----------------
# `launchctl bootout` returns as soon as it has told the agent to go, not once it has
# gone: a `bootstrap` issued straight after fails with "Bootstrap failed: 5:
# Input/output error" while the old process is still on its way out. So this waits,
# bounded to 30s, until the agent is out of the domain and its process is gone. An
# agent that is not loaded is already stopped, not an error; any other bootout
# failure is shown, never silenced.
#
# THIS FUNCTION IS DUPLICATED, BYTE FOR BYTE, IN install.sh AND update.sh -- see
# write_uninstall_script above for why. Change one, change the other.
stop_launchd_agent() {
  local label="$1" domain listing pid _
  domain="gui/$(id -u)/$label"
  if ! listing="$(launchctl print "$domain" 2>/dev/null)"; then
    return 0
  fi
  pid="$(printf '%s\n' "$listing" | sed -n 's/^[[:space:]]*pid = \([0-9][0-9]*\).*/\1/p' | head -n 1)"
  launchctl bootout "$domain"
  for _ in $(seq 1 30); do
    if ! launchctl print "$domain" >/dev/null 2>&1 \
        && { [ -z "$pid" ] || ! kill -0 "$pid" 2>/dev/null; }; then
      return 0
    fi
    sleep 1
  done
  # The grace period is over (#676): finish the job the way systemd's own stop does --
  # SIGKILL, to the service if launchd still has it and to the pid directly -- then a
  # few seconds more. Gone is a stop, said to have been forced; still there is an error
  # that names what is left, so the next report is not as blind as the one before it.
  echo "The server has not exited after 30s -- forcing it."
  launchctl kill SIGKILL "$domain" 2>/dev/null || true
  if [ -n "$pid" ]; then
    kill -KILL "$pid" 2>/dev/null || true
  fi
  for _ in $(seq 1 10); do
    if ! launchctl print "$domain" >/dev/null 2>&1 \
        && { [ -z "$pid" ] || ! kill -0 "$pid" 2>/dev/null; }; then
      echo "Stopped (forced after 30s: the server ignored SIGTERM)."
      return 0
    fi
    sleep 1
  done
  {
    echo "error: the launchd agent $label did not stop, even when forced."
    if launchctl print "$domain" >/dev/null 2>&1; then
      echo "  agent: still loaded in $domain"
    else
      echo "  agent: unloaded"
    fi
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
      echo "  server pid $pid: still alive"
      echo "  its children: $(pgrep -P "$pid" 2>/dev/null | tr '\n' ' ')"
    else
      echo "  server pid ${pid:-?}: gone"
    fi
  } >&2
  return 1
} # end stop_launchd_agent

# --- Stopping whatever is running (#385, #386, #647) ----------------------------
# Stops the instance the way it was started -- the service manager's own stop, or the
# pid a detached start recorded -- and returns once it is gone. A missing pid file, or
# a pid that is no longer running, is not an error: there is simply nothing to stop.
#
# THIS FUNCTION IS DUPLICATED, BYTE FOR BYTE, IN install.sh AND update.sh -- see
# write_uninstall_script above for why. Change one, change the other.
stop_running_server() {
  local kind="$1" dir="$2" label="$3" pid_file old_pid _
  pid_file="$dir/locklane.pid"
  case "$kind" in
    systemd)
      echo "Stopping the locklane service..."
      systemctl --user stop locklane
      ;;
    launchd)
      echo "Stopping the locklane agent..."
      stop_launchd_agent "$label"
      ;;
    *)
      if [ -f "$pid_file" ]; then
        old_pid="$(cat "$pid_file")"
        if [ -n "$old_pid" ] && kill -0 "$old_pid" 2>/dev/null; then
          echo "Stopping the running server (pid $old_pid)..."
          kill "$old_pid"
          for _ in $(seq 1 30); do
            kill -0 "$old_pid" 2>/dev/null || break
            sleep 1
          done
          if kill -0 "$old_pid" 2>/dev/null; then
            echo "error: server (pid $old_pid) did not stop within 30s." >&2
            return 1
          fi
        fi
        rm -f "$pid_file"
      fi
      ;;
  esac
} # end stop_running_server

# --- Downloading the jar before anything is stopped (#647) ----------------------
# Fetches the newest permanent release's locklane.jar (no tag argument: gh resolves the
# newest non-prerelease, non-draft release, the one the in-app update banner announces,
# #465) to locklane.jar.new next to the live jar, and checks that it is a readable
# archive -- so a failed or truncated download is found while the old server is still
# running, and never replaces a working jar. `unzip -tq` where unzip exists; otherwise
# the zip signature plus a size no Spring Boot jar is under.
#
# THIS FUNCTION IS DUPLICATED, BYTE FOR BYTE, IN install.sh AND update.sh -- see
# write_uninstall_script above for why. Change one, change the other.
download_jar() {
  local repo="$1" dir="$2" new size
  new="$dir/locklane.jar.new"
  rm -f "$new"
  echo "Downloading locklane.jar (newest release of $repo)..."
  if ! gh release download --repo "$repo" --pattern locklane.jar --output "$new"; then
    rm -f "$new"
    echo "error: could not download locklane.jar -- nothing was changed." >&2
    return 1
  fi
  if command -v unzip >/dev/null 2>&1; then
    if ! unzip -tq "$new" >/dev/null 2>&1; then
      rm -f "$new"
      echo "error: the downloaded locklane.jar is not a readable archive -- nothing was changed." >&2
      return 1
    fi
  else
    size="$(wc -c < "$new" | tr -d '[:space:]')"
    if [ "$(head -c 2 "$new")" != "PK" ] || [ "$size" -lt 1048576 ]; then
      rm -f "$new"
      echo "error: the downloaded locklane.jar is not a readable archive -- nothing was changed." >&2
      return 1
    fi
  fi
} # end download_jar

# Rewrites (or, on a pre-#422 install, adds) the systemd unit's Environment=PATH= line
# with a freshly resolved value -- so re-running update.sh repairs an already-broken
# service without a reinstall. Rewritten line by line rather than with sed: the PATH
# value is attacker-free but arbitrary, and this sidesteps having to escape it for a
# sed pattern/replacement or an `a` command's own text-continuation rules.
#
# Two distinct passes, not one combined pass: a combined pass that both replaces an
# existing `Environment=PATH=` line and inserts one after `[Service]` double-writes it
# when a unit already has the line, since it hits both the `[Service]` and the
# `Environment=PATH=` cases for the same file.
update_systemd_path() {
  local unit="$1" path_value="$2" tmp line
  tmp="$(mktemp "$unit.XXXXXX")"
  if grep -q '^Environment=PATH=' "$unit"; then
    while IFS= read -r line || [ -n "$line" ]; do
      case "$line" in
        Environment=PATH=*) printf 'Environment=PATH=%s\n' "$path_value" ;;
        *) printf '%s\n' "$line" ;;
      esac
    done < "$unit" > "$tmp"
  else
    while IFS= read -r line || [ -n "$line" ]; do
      printf '%s\n' "$line"
      if [ "$line" = '[Service]' ]; then
        printf 'Environment=PATH=%s\n' "$path_value"
      fi
    done < "$unit" > "$tmp"
  fi
  mv "$tmp" "$unit"
}

# Rewrites (or, on a pre-#422 install, adds) the launchd plist's EnvironmentVariables
# PATH entry with a freshly resolved value, via PlistBuddy -- the standard macOS tool
# for editing a plist without hand-rolling XML, and one that handles a PATH value
# containing spaces or colons correctly as long as it's quoted in the command string.
update_launchd_path() {
  local plist="$1" path_value="$2"
  /usr/libexec/PlistBuddy -c "Delete :EnvironmentVariables" "$plist" >/dev/null 2>&1 || true
  /usr/libexec/PlistBuddy -c "Add :EnvironmentVariables dict" "$plist"
  /usr/libexec/PlistBuddy -c "Add :EnvironmentVariables:PATH string \"$path_value\"" "$plist"
}

# Adds SuccessExitStatus=143 to a unit that lacks it (#647), so a unit written before
# install.sh carried the line stops logging every stop as a failure. The same
# line-by-line rewrite as update_systemd_path, its own pass: a unit that already has a
# SuccessExitStatus line is left exactly as it is, so running this twice adds nothing.
update_systemd_success_status() {
  local unit="$1" tmp line
  if grep -q '^SuccessExitStatus=' "$unit"; then
    return 0
  fi
  tmp="$(mktemp "$unit.XXXXXX")"
  while IFS= read -r line || [ -n "$line" ]; do
    printf '%s\n' "$line"
    if [ "$line" = '[Service]' ]; then
      printf 'SuccessExitStatus=143\n'
    fi
  done < "$unit" > "$tmp"
  mv "$tmp" "$unit"
}

# --- Detect how the server was started (#386) -----------------------------------
# install.sh sets up a systemd user service or a launchd agent when the platform
# supports one, falling back to #385's plain detached start otherwise. Whichever it
# is, this script must stop and restart it the same way — never leave the service
# running while also launching a second, competing copy by hand.

unit_file="$HOME/.config/systemd/user/locklane.service"
agent_label="com.locklane.server"
agent_file="$HOME/Library/LaunchAgents/$agent_label.plist"
if [ -f "$unit_file" ] && command -v systemctl >/dev/null 2>&1; then
  service_kind="systemd"
elif [ -f "$agent_file" ] && command -v launchctl >/dev/null 2>&1; then
  service_kind="launchd"
else
  service_kind=""
fi

# --- Refuse to run from inside the server (#647) ---------------------------------
# Before anything else has changed: a console tab's shell would die at the stop step
# below, with the server stopped and nothing left to restart it.
refuse_inside_server "$service_kind" update.sh "$agent_label"

# gh must be installed, not logged in: the only gh calls below are `gh release download`
# and `gh release view`, which work unauthenticated on a public repository (#610).
if ! command -v gh >/dev/null 2>&1; then
  echo "error: the GitHub CLI (gh) is required — install it from https://cli.github.com." >&2
  exit 1
fi

# --- Refresh this script first (#647) --------------------------------------------
# The jar is not the only thing a release changes: this script is how an install is
# kept current, and an install made before the code-server step (#628), or before this
# very block, would otherwise never get them. So the newest release's own update.sh is
# fetched first and, when it differs from this copy, takes over the run -- once,
# guarded by the variable, so a copy can never chase itself. Releases cut before #647
# carry no update.sh asset; that is not an error, the installed copy simply continues.
if [ -z "${LOCKLANE_UPDATE_REEXEC:-}" ]; then
  new_self="$(mktemp update.sh.XXXXXX)"
  if gh release download --repo "$REPO" --pattern update.sh \
      --output "$new_self" --clobber 2>/dev/null && [ -s "$new_self" ]; then
    if cmp -s "$new_self" update.sh; then
      rm -f "$new_self"
    else
      echo "The newest release carries a newer update.sh -- switching to it for this run..."
      chmod 755 "$new_self"
      mv -f "$new_self" update.sh
      LOCKLANE_UPDATE_REEXEC=1 exec ./update.sh
    fi
  else
    rm -f "$new_self"
    echo "No update.sh on the newest release (or it could not be fetched); keeping the installed copy."
  fi
fi

# --- Refresh the service's PATH (#422) and make a stop count as success (#647) ----
# Done here, before anything else touches the service, so an already-broken install
# is repaired by this run whether or not a newer jar is even available yet.
case "$service_kind" in
  systemd)
    echo "Refreshing the systemd service's PATH..."
    update_systemd_path "$unit_file" "$(resolve_login_path)"
    update_systemd_success_status "$unit_file"
    systemctl --user daemon-reload 2>/dev/null || true
    ;;
  launchd)
    echo "Refreshing the launchd agent's PATH..."
    update_launchd_path "$agent_file" "$(resolve_login_path)"
    ;;
esac

# --- Retire a stored bootstrap password ---------------------------------------
# Installs predating #384 left the login password in plaintext here. The engine
# consumed it on its very first start and has ignored it ever since, so the value is
# dead — drop that one line and leave every other byte of the file as it was.

props_file="application-locklane.properties"
if [ -f "$props_file" ] && grep -Eq '^locklane\.security\.bootstrap-password[[:space:]]*=' "$props_file"; then
  echo "Removing the stored bootstrap password from $props_file..."
  tmp_props="$(mktemp "$props_file.XXXXXX")"
  chmod 600 "$tmp_props"
  sed -E '/^locklane\.security\.bootstrap-password[[:space:]]*=/d' "$props_file" > "$tmp_props"
  mv "$tmp_props" "$props_file"
fi

# --- Download and verify the new jar while the old server keeps running (#647) ---
# Everything that can fail on the network fails here, with the old server untouched.
# The tag is read now, next to the download, so the line printed at the end names the
# release that was actually fetched. `gh release view` needs a logged-in gh, which this
# host need not have (#610), so an unauthenticated read of the same "latest" release
# through the REST API is the fallback; failing both is not worth failing the run.
tag="$(gh release view --repo "$REPO" --json tagName -q .tagName 2>/dev/null)" || tag=""
if [ -z "$tag" ]; then
  tag="$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest" 2>/dev/null \
    | sed -n 's/^[[:space:]]*"tag_name":[[:space:]]*"\([^"]*\)".*/\1/p' | head -n 1)" || tag=""
fi
download_jar "$REPO" "$(pwd)"

# --- Stop the running instance, then swap the jar in ------------------------------
# The stop happens only now, after the download has succeeded (#385, #647): overwriting
# locklane.jar while the running JVM still holds it open, then starting a second server
# on the port the first one still has bound, leaves the old server damaged and the new
# one not running -- and a stop before a download that then fails leaves nothing
# running at all.
if ! stop_running_server "$service_kind" "$(pwd)" "$agent_label"; then
  rm -f locklane.jar.new
  exit 1
fi
mv -f locklane.jar.new locklane.jar

# --- Start the new build ---------------------------------------------------------
# A service-managed install (#386) is restarted the same way it was started; the
# fallback (#385) relaunches detached the same way install.sh does: nohup ignores the
# SIGHUP the shell sends its children on exit, and disown drops it from the shell's own
# job table, the second, independent way a closing terminal can take a background job
# down with it.

pid_file="locklane.pid"
case "$service_kind" in
  systemd)
    echo "Restarting the locklane service..."
    systemctl --user start locklane
    ;;
  launchd)
    echo "Restarting the locklane agent..."
    launchctl bootstrap "gui/$(id -u)" "$agent_file"
    ;;
  *)
    log_file="locklane.log"
    echo "Relaunching..."
    nohup java -jar locklane.jar > "$log_file" 2>&1 < /dev/null &
    echo $! > "$pid_file"
    disown
    ;;
esac
echo "Installed locklane ${tag:-(version unknown)} and restarted the server."

# --- code-server (#628) ---------------------------------------------------------
# Re-run install.sh's own installer: it detects the version already under --prefix
# and updates it in place, so this is a no-op on an install that already has the
# newest code-server. Kept in sync with install.sh's own copy of this block --
# CodeServerService resolves the binary at "code-server/bin/code-server" relative
# to this directory either way.
#
# Run after the server is already back up, not before, and soft-failing: this update
# already stopped the running server above to replace the jar, so getting it running
# again is the one thing this script cannot skip -- a code-server.dev hiccup here is
# an optional extra, and must never leave the server down over it (matching how
# install.sh orders and guards this same step).
echo "Installing code-server..."
if ! curl -fsSL https://code-server.dev/install.sh | sh -s -- \
  --method=standalone --prefix="$(pwd)/code-server"; then
  echo "warning: could not update code-server -- the \"Open IDE\" console action may be stale or missing until the next update.sh run." >&2
fi

# --- Refresh the uninstaller (#392) and the control scripts (#612) ---------------
# Rewritten on every update so an install never keeps a stale copy -- one generated
# before the service kind changed would de-register, stop or start the wrong thing, or
# nothing.

case "$service_kind" in
  systemd) reg_file="$unit_file" ;;
  launchd) reg_file="$agent_file" ;;
  *) reg_file="" ;;
esac
write_uninstall_script "$(pwd)" "$service_kind" "$reg_file"
write_control_scripts "$(pwd)" "$service_kind" "$reg_file"
